@WebClientBffGateway_HostAddress = http://localhost:7810


### ADD NEW PATIENT ###
POST {{WebClientBffGateway_HostAddress}}/patient
Accept: application/json
Content-Type: application/json

{
  "firstName": "Naama",
  "lastName": "Dahan",
  "dateOfBirth": "2015-01-08",
  "gender": "Male",
  "address": "Jerusalem"
}

### GET ALL PATIENTS ###
GET {{WebClientBffGateway_HostAddress}}/patient
Accept: application/json
Content-Type: application/json

### SET CURRENT VITAL ###
POST {{WebClientBffGateway_HostAddress}}/vitals/current
Accept: application/json
Content-Type: application/json

{
  "patientId": 1,
  "vitalsData": {
    "temperature": 37.4,
    "bloodPressure": {
      "systolic": 120,
      "diastolic": 85
    },
    "heartRate": 102,
    "respiratoryRate": 16,
    "oxygenSaturation": 98
  }
}

### GET PATEIENT HISTORY###

GET {{WebClientBffGateway_HostAddress}}/history/1
Accept: application/json
Content-Type: application/json
