@WebClientBffGateway_HostAddress = http://localhost:7810


### ADD NEW PATIENT ###
POST {{WebClientBffGateway_HostAddress}}/patient
Accept: application/json
Content-Type: application/json

{
  "firstName": "DAS",
  "lastName": "Menachem2",
  "dateOfBirth": "2012-01-08",
  "gender": "Male",
  "address": "Jerusalem"
}

### GET ALL PATIENTS ###
GET {{WebClientBffGateway_HostAddress}}/patient
Accept: application/json
Content-Type: application/json

### SET CURRENT VITAL ###
POST {{WebClientBffGateway_HostAddress}}/vitals/current
Accept: application/json
Content-Type: application/json

{
  "patientId": 1,
  "vitalsData": "101"
}

### GET PATEIENT HISTORY###

GET {{WebClientBffGateway_HostAddress}}/history/1
Accept: application/json
Content-Type: application/json
